### ISSUE TITLE
App crash on launch

### ISSUE THREAD

**Issue by ejdoh1** [ipsn/go-ghostbridge#1]
Hi,

Was interested in getting your example running and ran into the following issue where after I run the final `react-native run-android` the app crashes with the following logs. Looking for ideas on how I can troubleshoot and fix. I am using an Android Emulator, thanks!

```
2019-03-06 01:18:01.446 6061-0/com.avatardemo E/Go: panic: runtime error: invalid memory address or nil pointer dereference
2019-03-06 01:18:01.446 6061-0/com.avatardemo E/Go: [signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0xd52d2ba9]
2019-03-06 01:18:01.446 6061-0/com.avatardemo E/Go: goroutine 17 [running, locked to thread]:
2019-03-06 01:18:01.446 6061-0/com.avatardemo E/Go: github.com/ipsn/go-ghostbridge.(*Bridge).Port(0xa4c449e0, 0xd53b0f60)
2019-03-06 01:18:01.446 6061-0/com.avatardemo E/Go: 	C:/Users/username/go/src/github.com/ipsn/go-ghostbridge/ghostbridge.go:103 +0x19
2019-03-06 01:18:01.446 6061-0/com.avatardemo E/Go: main.proxyghostbridge_Bridge_Port(0xffffffe8, 0xa4c003c8, 0x3)
2019-03-06 01:18:01.447 6061-0/com.avatardemo E/Go: 	C:/Users/username/AppData/Local/Temp/gomobile-work-318865607/src/gobind/go_ghostbridgemain.go:49 +0x46
2019-03-06 01:18:01.447 6061-6080/com.avatardemo E/GoLog: panic: runtime error: invalid memory address or nil pointer dereference
2019-03-06 01:18:01.447 6061-0/com.avatardemo E/Go: main._cgoexpwrap_f91d87702665_proxyghostbridge_Bridge_Port(0xffffffe8, 0x24d6, 0xf0392084)
2019-03-06 01:18:01.447 6061-0/com.avatardemo E/Go: 	_cgo_gotypes.go:188 +0x1b
2019-03-06 01:18:01.447 6061-6061/com.avatardemo A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 6061 (com.avatardemo), pid 6061 (com.avatardemo)
```

**Comment by karalabe** [comment]
How does your java file look like? Could you paste it here? And your Go one?

**Comment by ejdoh1** [comment]
Apologies - I was being a spud and did not create the go avatars package as per the instructions.
Got it working, it's awesome - thanks!

**Comment by ghost** [comment]
@ejdoh1 would you mind to provide me a sample repo? I'm trying to make it work here.
